### ISSUE TITLE
package.xml vs colcon.pkg

### ISSUE THREAD

**Issue by spiderkeys** [colcon/colcon.readthedocs.org#44]
Regarding the following page:
https://colcon.readthedocs.io/en/released/user/configuration.html#colcon-pkg-files

It mentions that the project must have a colcon.pkg file, which has the name, type, dependencies, etc. fields, but I can't find any examples of such a file in any projects that I've come across that use Colcon. What I do see is the use of package.xml file for these values, as one would typically encounter in ROS projects. As an example, looking at a driver in the Autoware project:

https://gitlab.com/AutowareAuto/AutowareAuto/tree/master/src/drivers/udp_driver

I see a package.xml file, but no colcon.pkg file. Is there a typo in the docs, or are the package.xml and colcon.pkg files complimentary and/or alternatives? Additionally, are there any example colcon based projects that demonstrate the latest best practices?

**Comment by dirk-thomas** [comment]
> Is there a typo in the docs, or are the package.xml and colcon.pkg files complimentary and/or alternatives?

A `colcon.pkg` file is only used to provide additional metadata for a package if they are not available otherwise. If a package has a ROS `package.xml` file that is sufficient and it doesn't need a `colcon.pkg` file. So commonly they are alternatives (even though they can be complimentary, e.g. to include information in the `colcon.pkg` which a ROS `package.xml` file can't provide).

> A colcon.pkg file must be placed in the root directory of a package.

The sentence in the document refers to the fact that - if a `colcon.pkg` file is being used - it must be places in the root directory of the package. I can see how this can be confusing. Please feel free to propose a pull request to rephrase the specific section in question.

**Comment by spiderkeys** [comment]
I see, thanks for the clarification. After I get a bit more spun up with how colcon works, I will think of how this could best be worded and open a PR :)

**Comment by dirk-thomas** [comment]
@spiderkeys Friendly ping. Are you still planning to contribute your thoughts to the docs?

**Comment by spiderkeys** [comment]
Thanks for the ping @dirk-thomas, this totally fell off the radar. Still want to contribute and will put this on my list of items for next week.

**Comment by dirk-thomas** [comment]
> will put this on my list of items for next week.

@spiderkeys Friendly ping.

**Comment by dirk-thomas** [comment]
@spiderkeys Friendly ping.

**Comment by spiderkeys** [comment]
@dirk-thomas Apologies on the delays; I haven't been working on the ROS2/Colcon aspects of our projects lately so I will need to get spun back up. I'm diving back into using Colcon pretty heavily in my current project, so I should be able to provide resolution on this (and hopefully provide additional feedback) soon.

**Comment by dirk-thomas** [comment]
I will go ahead and close the ticket for now since it is not clear what exact changes are desired. Please feel free to contribute to the docs when you have time.
